---

- name: Install packages
  apt:
    state: present
    name:
      - python3-hvac
  become: true

- name: login to vault
  community.hashi_vault.vault_login:
    auth_method: userpass
    username: "nolan.djellal"
    password: "{{ lookup('env', 'VAULT_PASSWORD') }}"
    url: "https://vault.srs.epita.fr/"
  register: vault_login
  changed_when: False
